server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mariadb://192.168.20.33:3306/mar_platform
    username: root
    password: Tpc@123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
